### PR TITLE
Show live download and upload progress

### LINKED ISSUE #7: Show current download speed during the test
In SpeedTest site I can understand average download speed even before test is finished, because it shows current download speed. It is not accurate, but enough in many cases.

### PR DESCRIPTION
**Pull request by SamVerschueren**
Same as PR https://github.com/sindresorhus/speed-test/pull/19 but with the following format.

screen shot 2015-09-28 at 17 40 34
screen shot 2015-09-28 at 17 39 25
screen shot 2015-09-28 at 17 39 46

-

Fixes #7.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Awesome! I like this one the best. I would still like to have the spinner for each step though. How about having it in the middle? Would it make sense to make it yellow too? Or gray?

screen shot 2015-09-29 at 20 54 55


```patch
iff --git a/cli.js b/cli.js
index bf7cc395e0e116ad30908ce54838794b3d4b62aa..2cbc96facea658f93645458fc38e2967f9f0bc06 100755
--- a/cli.js
+++ b/cli.js
@@ -30,7 +30,7 @@ var state = 'ping';
 var frame = elegantSpinner();
 
 function getSpinner(x) {
-	return state === x ? chalk.cyan.dim(frame()) : '';
+	return state === x ? chalk.cyan.dim(frame()) : ' ';
 }
 
 function render() {
@@ -41,9 +41,9 @@ function render() {
 
 	logUpdate([
 		'',
-		'      Ping  ' + getSpinner('ping') + stats.ping,
-		'  Download  ' + stats.download,
-		'    Upload  ' + stats.upload
+		'      Ping ' + getSpinner('ping') + ' ' + stats.ping,
+		'  Download ' + getSpinner('download') + ' ' + stats.download,
+		'    Upload ' + getSpinner('upload') + ' ' + stats.upload
 	].join('\n'));
 }
 ```

**Comment by sindresorhus** [comment]
Also noticed that it takes some time before the live download/upload speed is shown. Maybe show `0 Mbps` there in the meantime so it's not empty?

**Comment by SamVerschueren** [comment]
Made the changes. Let me know if you want other adjustments as well.

I didn't make the spinner gray (yet). It's okay to me to keep it cyan. What do you think?

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by SamVerschueren** [comment]
Spinner color makes sense :).

We just have to change the gif though. But I think it's not that easy to do that?

**Comment by sindresorhus** [comment]
Oh noes :p I'm not changing the gif until I'm certain this is how I want it. The gif took longer than the module itself...

**Comment by SamVerschueren** [comment]
Hahaha, already thought it was difficult to make :p.

**Pull request closed without merging**
